# Generated by Django 3.1.6 on 2021-02-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Název kategorie')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Název')),
                ('count', models.IntegerField(default=0, verbose_name='Počet')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Datum změny')),
                ('category', models.ManyToManyField(to='items.Category')),
            ],
            options={
                'verbose_name': 'Položka',
                'verbose_name_plural': 'Položky',
            },
        ),
    ]
