# Generated by Django 3.1.6 on 2021-02-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('m', 'Metry'), ('ks', 'Kusy'), ('cm', 'Centimetry')], default='ks', max_length=4, verbose_name='Jednotka'),
        ),
    ]
