# Generated by Django 3.1.6 on 2021-02-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Cena za jednotku'),
        ),
    ]
