# Generated by Django 3.1.6 on 2021-04-15 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20210415_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.supplier', verbose_name='supplier'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name of subcategory')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'subcategory',
                'verbose_name_plural': 'subcategories',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ManyToManyField(to='items.SubCategory', verbose_name='subcategories'),
        ),
    ]
