# Generated by Django 3.2.2 on 2021-05-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20210415_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='items.SubCategory', verbose_name='subcategories'),
        ),
    ]
