# Generated by Django 3.2.2 on 2021-05-20 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0010_alter_item_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price per unit')),
                ('STATUS', models.CharField(choices=[('res', 'reserved'), ('fin', 'finished')], default='res', max_length=3, verbose_name='status')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item', verbose_name='item')),
            ],
        ),
    ]
